### ISSUE TITLE
Specification error found in callback of /v1/read-current-mac-table-from-device for sending answer to requestor

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/MacAddressTableRecorder#226]
The schema of callback `PromptForUpdatingMacTableFromDeviceCausesSendingAnswerToRequestor` does not match the example.

The schema outlines, that the requestBody consists of an array where every record has properties:
- request-id
- mount-name
- own-mac-address
- egress-ltp-uuid
- original-ltp-name
- vlan-id
- remote-mac-address
- time-stamp-of-data

But in the example the request-id is completely missing:
```
                        - mount-name: "305251234"
                          own-mac-address: "00:00:00:00:00:00"
                          egress-ltp-uuid: "305251234+mac-inf-1234"
                          original-ltp-name: "eth-1-0-3"
                          vlan-id: 17
                          remote-mac-address: "01:01:01:01:01:01"
                          time-stamp-of-data: "2010-11-20T14:00:00+01:00"
                        - mount-name: "305251234"
                          own-mac-address: "00:00:00:00:00:00"
                          egress-ltp-uuid: "305251234+mac-inf-1234"
                          original-ltp-name: "eth-1-0-3"
                          vlan-id: 17
                          remote-mac-address: "FF:01:01:01:01:01"
                          time-stamp-of-data: "2010-11-20T14:00:00+01:00"
```

Moreover: it does not make sense to send the request-id in each array element (the only exception would be, if the answer would be bundled for multiple requests to different devices opposed to sending an own anser for each device/read-current-mac-address call).

Therefore the schema should look as follows (would be needed into proper yaml notation):
```
schema:
  type: object
  properties:
    - request-id: type=string
    - mac-address-data: type = array
      items: mount-name, own-mac-address, egress-ltp-uuid, original-ltp-name, vlan-id, remote-mac-address, time-stamp-of-data
```
