### ISSUE TITLE
No errorResponse for invalid requestBody for /v1/read-current-mac-table-from-device (requestorProtocol)

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/MacAddressTableRecorder#227]
When the service is called with a random requestorProtocol string it should return an error (guess it should be a 400, bad request), as per specification it must be HTTP or HTTPs. 
However, the service currently returns a 200 and the requestId.

Spec:
```
                    requestor-protocol:
                      type: string
                      description: >
                        'HTTP or HTTPs protocol for sending the response to the requestor'
                      enum:
                        - "HTTP"
                        - "HTTPS"
```
![image](https://github.com/user-attachments/assets/289ee983-3a2e-426b-a8c3-10cb22a3dbca)
