### ISSUE TITLE
No errorResponse for invalid requestBody for /v1/read-current-mac-table-from-device (requestorAddress)

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/MacAddressTableRecorder#228]
The requestorAddress must look like either of the two examples:
```
requestor-address:
  ip-address:
    ipv-4-address: "1.1.4.1"

requestor-address:
  domain-name: "subdomain.example.com"
```
However, if the address in the requestBody does not match that format, I still see a 200 being returned.
Instead this should return an error (guess again 400).

![image](https://github.com/user-attachments/assets/d0d97c5f-6d89-4446-a908-1f8b961f6ac3)
