### ISSUE TITLE
StringProfile for controller internal URI segment

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/MacAddressTableRecorder#55]
Background:
- There shall be no difference in addressing the MWDI or the controller NBI for retrieving device information.
- If the devices get addressed via the controller NBI, there is a URI segment that represents the data structure inside the controller between TCP port and mount point.
- At the current OpenDaylight controller, this URI segment is "/rests/data/network-topology:network-topology/topology=topology-netconf/".
- In general, this URI segment is individual to the controller.
- It is planned to shorten this URI segment to "" (empty string) in case of the MWDI.
- If we would switch between controllers or between controller and MWDI, all OperationClients addressing the controller/MWDI would need to be updated.
- This change would effect all applications addressing the controller/MWDI.

**Proposal:**
- It is proposed to add two instances of StringProfile for holding this URI segment and to reference these instances of StringProfile whenever a URI to the controller or the MWDI needs to be composed.

Changes:
- ProfileList needs to be completed by StringProfile from ApplicationPattern
- ProfileInstanceList needs to be completed by:
  ```
  - profile-name: 'StringProfile'
    uuid: 'matr-1-0-0-string-p-000'
    capability:
      string-name: 'mwdiInternalPathToMountPoint'
    configuration:
      string-value: '/rests/data/network-topology:network-topology/topology=topology-netconf'
  - profile-name: 'StringProfile'
    uuid: 'matr-1-0-0-string-p-001'
    capability:
      string-name: 'controllerInternalPathToMountPoint'
    configuration:
      string-value: ''
   ```   
- ServiceList needs to be changed to:
   ```
  - http-client:
      application-name: MicroWaveDeviceInventory
      release-number: 1.0.0
      uuid: matr-1-0-0-http-c-mwdi-1-0-0-000
    tcp-client:
      remote-protocol: http
      ip-address: 1.1.4.4
      tcp-port: 4004
      uuid: matr-1-0-0-tcp-c-mwdi-1-0-0-000
    operation-clients:
      own-oam:
        basic:
        individual:
      service:
        basic:
        individual:
          - operation-name: {matr-1-0-0-string-p-000}/?fields=node(node-id)
            uuid: matr-1-0-0-op-c-is-mwdi-1-0-0-000
          - operation-name: {matr-1-0-0-string-p-000}/node={mount-name}/yang-ext:mount/core-model-1-4:control-construct/logical-termination-point={uuid}/ltp-augment-1-0:ltp-augment-pac?fields=original-ltp-name
            uuid: matr-1-0-0-op-c-is-mwdi-1-0-0-001
          - operation-name: {matr-1-0-0-string-p-000}/node={mount-name}/yang-ext:mount/core-model-1-4:control-construct?fields=forwarding-domain(uuid;layer-protocol-name)
            uuid: matr-1-0-0-op-c-is-mwdi-1-0-0-002
          - operation-name: {matr-1-0-0-string-p-000}/node={mount-name}/yang-ext:mount/core-model-1-4:control-construct/forwarding-domain={uuid}/mac-fd-1-0:mac-fd-pac/mac-fd-status?fields=mac-address-cur
            uuid: matr-1-0-0-op-c-is-mwdi-1-0-0-003
  - http-client:
      application-name: OpenDaylight
      release-number: 4.0.2
      uuid: matr-1-0-0-http-c-odl-4-0-2-000
    tcp-client:
      remote-protocol: http
      ip-address: 1.1.1.1
      tcp-port: 1001
      uuid: matr-1-0-0-tcp-c-odl-4-0-2-000
    operation-clients:
      own-oam:
        basic:
        individual:
      service:
        basic:
        individual:
          - operation-name: {matr-1-0-0-string-p-001}/node={mount-name}/yang-ext:mount/mac-fd-1-0:provide-learned-mac-addresses
            uuid: matr-1-0-0-op-c-is-odl-4-0-2-000
   ```
- OAS needs to be corrected in several URIs in the callbacks
- OAS needs to be complemented by OAM paths for managing StringProfile
- CONFIGfile needs to be complemented by two instances of StringProfile.
- CONFIGfile needs to be corrected in the OperationClients to the controller and to the MWDI.

(This list might be incomplete.)
